name: Angular CI/CD

on:
  push:
    branches: [ dev ]

env:
  NODE_VERSION: 18

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [$NODE_VERSION]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci

    - name: Install dependencies
      run: npm install

    - name: Build application
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.TOKEN }}
        publish_dir: dist/my-angular-app
