name: Angular CI/CD

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
      
    - name: Install dependencies
      run: npm ci

    - name: Install node modules
      run: npm install

    - name: Build application
      run: npm run build

    - name: Push Build to Releases
      uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/angular-githubaction/*"
        token: ${{ secrets.TOKEN }}